# Generated by Django 3.2.5 on 2021-07-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('WATERED_ON', 'Watered on'), ('REPOTTED_ON', 'Repotted On'), ('FERTILIZED_ON', 'Fertilized On'), ('PEST_TREATMENT', 'Treated for pests')], default=None, max_length=50)),
                ('carried_on', models.DateField()),
            ],
        ),
    ]
