# Generated by Django 3.2.5 on 2021-07-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenance_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='task',
            field=models.CharField(choices=[('WATERED ON', 'Watered on'), ('REPOTTED ON', 'Repotted On'), ('FERTILIZED ON', 'Fertilized On'), ('PEST TREATMENT', 'Treated for pests')], default=None, max_length=50),
        ),
    ]
