# Generated by Django 3.2.5 on 2021-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
