# Generated by Django 3.2.5 on 2021-07-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.CharField(default='https://res.cloudinary.com/inetab/image/upload/c_scale,h_400,w_600/v1627030331/SEI_Project_4/sblkzvbotq3ndadygtsy.jpg', max_length=100),
        ),
    ]
