# Generated by Django 3.2.5 on 2021-07-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='nursery_pot',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
